### ISSUE TITLE
Having problem copying text

### ISSUE THREAD

**Issue by lesaff** [NinjasCL/InputfieldImageMarkdownCodeAdditionalFields#1]
This is a very useful module, thanks for doing it.

I am having problem copying the text from my end.

Module suggestion: Add a Javascript to copy directly to the clipboard.

Cheers
Rudy

**Comment by clsource** [comment]
Great idea.
I will add a special button 👍 
thanks.

**Comment by clsource** [comment]
![1](https://user-images.githubusercontent.com/292738/27065963-ba953c62-4fce-11e7-864d-f58c05ab1272.png)
![2](https://user-images.githubusercontent.com/292738/27065965-ba9a95b8-4fce-11e7-81b8-58fc47b78e96.png)
![3](https://user-images.githubusercontent.com/292738/27065964-ba9a835c-4fce-11e7-8127-8c5c307d2634.png)

Done! 💯
